apiVersion: openchoreo.dev/v1alpha1
kind: EnvSettings
metadata:
  name: web-service-prod
spec:
  componentRef:
    name: web-service
    namespace: default
  environment: production

  # Override component envOverrides for prod
  overrides:
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 2Gi

  # Override addon envOverrides by instanceId
  addonOverrides:
    # Override PVC addon (instanceId: app-data)
    app-data:
      size: 100Gi
      storageClass: premium

    # Override sidecar addon (instanceId: logger)
    logger:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi

    # Override emptydir addon (instanceId: shared-logs)
    shared-logs:
      sizeLimit: 5Gi
      medium: Memory
