apiVersion: apps/v1
kind: Deployment
metadata:
    name: web-service
    namespace: default
spec:
    replicas: 2
    selector:
        matchLabels:
            openchoreo.io/component-id: web-service-12345
            openchoreo.io/environment: production
            openchoreo.io/project-id: my-project-67890
    template:
        metadata:
            labels:
                app: web-service
                openchoreo.io/component-id: web-service-12345
                openchoreo.io/environment: production
                openchoreo.io/project-id: my-project-67890
        spec:
            containers:
                - image: gcr.io/my-project/web-service:v1.0.0
                  imagePullPolicy: IfNotPresent
                  name: app
                  resources:
                    limits:
                        cpu: 500m
                        memory: 512Mi
                    requests:
                        cpu: 100m
                        memory: 256Mi
---
---
apiVersion: v1
data:
    APP_ENV: production
    LOG_LEVEL: info
    MAX_CONNECTIONS: "100"
kind: ConfigMap
metadata:
    name: web-service-env-config
    namespace: default
---
---
apiVersion: v1
data:
    config: |
        database:
        host: localhost
        port: 5432
kind: ConfigMap
metadata:
    name: web-service-config--etc-app-config-yaml
    namespace: default
---
---
apiVersion: v1
data:
    config: '{"featureA": true, "featureB": false}'
kind: ConfigMap
metadata:
    name: web-service-config--etc-app-feature-flags-json
    namespace: default
