apiVersion: openchoreo.dev/v1alpha1
kind: Addon
metadata:
  name: external-secret-refresh-with-add
spec:
  displayName: "ExternalSecret Refresh Interval"

  schema:
    parameters: {}
    envOverrides: {}

  patches:
    # Fast refresh for env secret stores
    - target:
        group: external-secrets.io
        version: v1beta1
        kind: ExternalSecretStore
        where: ${resource.metadata.name.endsWith("-secret-envs")}
      operations:
        - op: add
          path: /spec/refreshInterval
          value: "5m"

    # Default refresh interval for other secret stores
    - target:
        group: external-secrets.io
        version: v1beta1
        kind: ExternalSecretStore
        where: ${!resource.metadata.name.endsWith("-secret-envs")}
      operations:
        - op: add
          path: /spec/refreshInterval
          value: "1h"
