apiVersion: apps/v1
kind: Deployment
metadata:
    name: web-service
    namespace: default
spec:
    replicas: 2
    selector:
        matchLabels:
            app: web-service
    template:
        metadata:
            labels:
                app: web-service
        spec:
            containers:
                - image: gcr.io/my-project/web-service:v1.0.0
                  imagePullPolicy: IfNotPresent
                  name: app
                  resources:
                    limits:
                        cpu: 200m
                        memory: 256Mi
                    requests:
                        cpu: 50m
                        memory: 128Mi
                  volumeMounts:
                    - mountPath: /app/data
                      name: app-data-vol
                      readOnly: false
                      subPath: ""
            volumes:
                - name: app-data-vol
                  persistentVolumeClaim:
                    claimName: web-service-app-data
---
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: web-service-app-data
    namespace: default
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
    storageClassName: standard
